Repository mission-apprentissage/catalogue-apprentissage, pull requests merged in 2022-03, with the labels that each got.

#554 Feature/affelnet import key change
  server/src/common/utils/referenceUtils.js
  server/src/common/utils/rulesUtils.js
  server/src/http/routes/reglePerimetre.js
  server/src/jobs/affelnet/coverage.js
  server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
  server/src/jobs/formations/rcoConverter/tests/migrationFinder.test.js
  server/tests/unit/common/utils/rulesUtils.test.js
Labels: enhancement

#563 refactor: faster & cleaner siret-uai api
  server/src/common/model/swaggerSchema/formation.js
  server/src/http/routes/etablissement.js
Labels: enhancement

#564 chore: better typing
  server/src/common/model/schema/etablissement.d.ts
  server/src/logic/mappers/etablissementsMapper.js
Labels: documentation

#573 tests: add tests on tags history updater
  server/src/http/routes/parcoursup.js
  server/tests/unit/logic/updaters/tagsHistoryUpdater.test.js
  ui/src/common/components/Breadcrumb.jsx
  ui/src/common/components/formation/PublishModal.jsx
  ui/src/common/components/formation/PublishModal.test.js
  ui/src/pages/admin/ReconciliationPs/components/ReconciliationModalHeader.jsx
Labels: tests

#574 feat: Ajout de l'historique des statuts Affelnet et Parcoursup
  ui/src/common/components/Search/Search.js
  ui/src/common/components/formation/DescriptionBlock.jsx
  ui/src/common/components/formation/StatutHistoryBlock.jsx
  ui/src/common/components/formation/StatutHistoryBlock.test.js
  ui/src/pages/Etablissement/Etablissement.js
  ui/src/pages/Etablissement/Etablissement.test.js
  ui/src/pages/Formation/Formation.js
Labels: feature

#576 feat: add data rncp_outdated on trainings
  server/migrations/20220316165000-rncp-date.js
  server/package.json
  server/src/common/model/schema/formation/formation.js
  server/src/common/model/swaggerSchema/formation.js
  server/src/common/utils/rulesUtils.js
  server/src/jobs/affelnet/perimetre/controller.js
  server/src/jobs/parcoursup/perimetre/controller.js
  server/src/jobs/parcoursup/tests/perimetre.test.js
  server/src/jobs/scriptWrapper.js
  server/src/logic/mappers/cfdMapper.js
  server/tests/unit/common/utils/rulesUtils.test.js
  server/yarn.lock
  ui/src/common/components/Search/constantsFormations.js
  ui/src/common/components/formation/DescriptionBlock.jsx
  ui/src/common/components/formation/DescriptionBlock.test.js
  ui/src/common/components/formation/OrganismesBlock.test.js
  ui/src/pages/Catalogue/Catalogue.test.js
  ui/src/pages/Formation/Formation.test.js
Labels: feature

#565 fix: merge multi-site trainings on RCO key change
  server/src/jobs/affelnet/coverage.js
  server/src/jobs/formations/rcoConverter/converter/converter.js
  server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
  server/src/jobs/formations/rcoConverter/tests/migrationFinder.test.js
  server/src/logic/controller/reconciliation.js
Labels: enhancement

#587 fix: rncp import
  server/package.json
  server/src/common/utils/streamUtils.js
  server/yarn.lock
Labels: bug

#590 fix(perimetre): regle_complementaire was overriding commonRules "$and"
  server/src/common/utils/rulesUtils.js
  server/tests/unit/common/utils/rulesUtils.test.js
Labels: bug

#589 feat: standalone script to update qualiopi data only
  server/package.json
  server/src/jobs/etablissements/EtablissementsUpdater/index.js
  server/src/jobs/etablissements/EtablissementsUpdater/updater/updater.js
  server/src/jobs/oneshot/qualiopi/index.js
  server/yarn.lock
Labels: enhancement

#593 fix(tests): stub api entreprise check call
  server/src/jobs/etablissements/EtablissementsUpdater/tests/updater.test.js
Labels: tests

#596 fix: no closed establishment filter
  server/src/jobs/etablissements/EtablissementsUpdater/index.js
  server/src/jobs/oneshot/qualiopi/index.js
Labels: bug

#602 fix: bump tco to remove unused deps
  server/package.json
  server/src/common/utils/parcoursupUtils.js
  server/src/http/routes/upload.js
  server/src/jobs/etablissements/uai.js
  server/yarn.lock
Labels: dependencies

#606 chore: bump deps
  server/package.json
  server/src/common/mailer.js
  server/yarn.lock
  ui/package.json
  ui/yarn.lock
Labels: dependencies
