Repository mission-apprentissage/catalogue-apprentissage, pull requests merged in 2022-04, with the labels that each got.

#614 fix: fix multiple downloads on reactive search query change
  ui/src/common/components/Search/Search.js
  ui/src/common/components/Search/components/ExportButton.js
Labels: bug

#617 fix: N'affiche le badge Habilité RNCP que pour le catalogue Non règlementaire
  ui/src/common/components/HabiliteBadge.jsx
  ui/src/common/components/Search/Search.js
  ui/src/common/components/Search/components/CardListFormation/CardListFormation.js
  ui/src/common/components/formation/OrganismesBlock.jsx
Labels: enhancement

#612 feat: Ajout de la colonne Active / Inactive dans les exports de formations
  ui/src/common/components/Search/constantsFormations.js
Labels: feature

#619 Feature/clean deps
  server/package.json
  server/yarn.lock
  ui/package.json
  ui/yarn.lock
Labels: dependencies

#618 enhancement: Améliorations diverses UX
  server/src/http/middlewares/consumptionMiddleware.js
  server/src/jobs/esIndex/index.js
  server/src/jobs/scriptWrapper.js
  ui/.prettierignore
  ui/src/common/components/HabiliteBadge.jsx
  ui/src/common/components/InfoTooltip.jsx
  ui/src/common/components/QualiteBadge.jsx
  ui/src/common/components/Search/Search.js
  ui/src/common/components/Search/components/CardListFormation/CardListFormation.js
  ui/src/common/components/Search/components/Facet/Facet.js
  ui/src/common/components/Search/constantsFormations.js
  ui/src/common/components/formation/DescriptionBlock.jsx
  ui/src/common/components/formation/PublishModal.jsx
  ui/src/constants/annees.js
  ui/src/constants/departements.js
  ui/src/pages/layout/components/AlertMessage.js
  ui/src/theme/components/badge.js
Labels: enhancement

#595 feat: dual control
  server/.env.example
  server/.gitignore
  server/migrations/20220414084257-dual-control-early-reports.js
  server/package.json
  server/src/common/model/index.js
  server/src/common/model/schema/dualControlReport.d.ts
  server/src/common/model/schema/dualControlReport.js
  server/src/common/model/schema/index.js
  server/src/common/utils/rcoUtils.js
  server/src/jobs/formations/dualControl/assets/.gitkeep
  server/src/jobs/formations/dualControl/comparator.js
  server/src/jobs/formations/dualControl/importer.js
  server/src/jobs/formations/dualControl/index.js
  server/src/jobs/formations/dualControl/mapper.js
  server/src/jobs/formations/dualControl/parser.js
  server/src/jobs/formations/dualControl/tests/comparator.test.js
  server/src/jobs/formations/dualControl/tests/mapper.test.js
  server/src/jobs/formations/dualControl/tests/parser.test.js
  server/src/jobs/index.js
  server/yarn.lock
Labels: feature

#634 fix: sanitize upload filename
  server/package.json
  server/src/http/routes/upload.js
  server/yarn.lock
Labels: 🔒 security

#635 Feature/sanitize mongo queries
  server/package.json
  server/src/http/routes/alert.js
  server/src/http/routes/etablissementSecure.js
  server/yarn.lock
Labels: 🔒 security

#637 Feature/sanitize mongo queries
  server/src/common/utils/miscUtils.js
  server/src/common/utils/sanitizeUtils.js
  server/src/http/routes/alert.js
  server/src/http/routes/etablissement.js
  server/src/http/routes/etablissementSecure.js
  server/src/http/routes/formation.js
  server/src/http/routes/formationSecure.js
  server/src/http/routes/parcoursup.js
  server/src/http/routes/rcoFormation.js
  server/src/http/routes/reglePerimetre.js
  server/src/http/routes/reglePerimetreSecure.js
  server/src/http/routes/report.js
  server/src/http/routes/role.js
  server/src/http/routes/stats.js
  server/src/http/server.js
  server/tests/unit/common/utils/sanitizeUtils.test.js
Labels: 🔒 security

#638 fix: add rate limite to api routes
  server/package.json
  server/src/http/routes/auth.js
  server/src/http/routes/password.js
  server/src/http/server.js
  server/tests/integration/http/login-test.js
  server/tests/integration/http/password-test.js
  server/yarn.lock
Labels: 🔒 security

#640 fix: session cookie is not sent when requests come from another domain
  server/src/http/server.js
Labels: 🔒 security

#645 feat: show alert message during elastic index
  server/src/jobs/index.js
  server/src/jobs/scriptWrapper.js
Labels: 🎨 enhancement

#648 fix: ndjson apis
  server/src/http/routes/etablissement.js
  server/src/http/routes/formation.js
  server/tests/integration/http/etablissement-test.js
  server/tests/integration/http/formation.test.js
Labels: 🐛 bug

#649 hotfix: API perimetre rate limit
  server/src/http/server.js
Labels: 🐛 bug

#650 fix: queryAsRegex insensitive
  server/src/http/routes/formation.js
Labels: 🐛 bug
