Repository mission-apprentissage/catalogue-apprentissage, pull requests merged in 2022-02, with the labels that each got.

#496 feat: change matching strength order for parcoursup
  server/src/logic/controller/coverage.js
Labels: enhancement

#499 fix: fill PS id for validated match only (and not all match)
  server/migrations/20220204162750-match-validated-fill-ps-id.js
  server/package.json
  server/src/jobs/parcoursup/_migrationFillParcourSupId.js
Labels: bug

#493 feat: new affelnet file & refactor coverage algo
  server/migrations/20220207094442-drop-afreconciliation.js
  server/migrations/20220207094834-rm-fields-afformations.js
  server/migrations/20220208130238-rename-affelnet-formations.js
  server/migrations/20220208130845-rename-parcoursup-formations.js
  server/package.json
  server/src/common/model/index.js
  server/src/common/model/schema/afReconciliation.js
  server/src/common/model/schema/affelnetFormation.js
  server/src/common/model/schema/formation/formation.js
  server/src/common/model/schema/index.js
  server/src/common/model/schema/parcoursupFormation.js
  server/src/constants/status.js
  server/src/http/routes/affelnet.js
  server/src/http/routes/parcoursup.js
  server/src/http/routes/upload.js
  server/src/http/server.js
  server/src/jobs/affelnet/coverage.js
  server/src/jobs/affelnet/import/index.js
  server/src/jobs/affelnet/index.js
  server/src/jobs/affelnet/perimetre/controller.js
  server/src/jobs/affelnet/reconciliation.js
  server/src/jobs/affelnet/reference/controller.js
  server/src/jobs/affelnet/reference/index.js
  server/src/jobs/affelnet/tests/perimetre.test.js
  server/src/jobs/esIndex/esIndex.js
  server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
  server/src/jobs/oneshot/afFormation/export.js
  server/src/jobs/oneshot/afFormation/importer.js
  server/src/jobs/oneshot/afFormation/index.js
  server/src/jobs/oneshot/afFormation/missingCfd.js
  server/src/jobs/parcoursup/_migrationRaisonsRejet.js
  server/src/jobs/parcoursup/_updateMatchInfo.js
  server/src/jobs/parcoursup/coverage.js
  server/src/jobs/parcoursup/export/index.js
  server/src/jobs/parcoursup/importer.js
  server/src/jobs/parcoursup/perimetre/controller.js
  server/src/jobs/parcoursup/reportRejected.js
  server/src/jobs/parcoursup/tests/export.test.js
  server/src/jobs/parcoursup/tests/perimetre.test.js
  server/src/logic/controller/coverage.js
  server/src/logic/controller/reconciliation.js
  server/src/logic/mappers/reconciliationMapper.js
  server/src/logic/updaters/coverageUpdater.js
  server/src/logic/updaters/mnaFormationUpdater.js
  server/tests/globalSetup.js
  server/tests/unit/logic/mappers/reconciliationMapper.test.js
  server/yarn.lock
  ui/src/common/api/formation.js
  ui/src/common/components/formation/DescriptionBlock.test.js
  ui/src/common/components/formation/OrganismesBlock.test.js
  ui/src/common/components/formation/PublishModal.jsx
  ui/src/common/components/formation/PublishModal.test.js
  ui/src/constants/es.js
  ui/src/pages/Formation/Formation.test.js
  ui/src/pages/admin/ReconciliationPs/ReconciliationPs.test.js
  ui/src/pages/admin/ReconciliationPs/components/ReconciliationModalHeader.jsx
  ui/src/pages/perimetre/components/ExportButton.test.js
  ui/src/pages/perimetre/components/Line.test.js
  ui/src/pages/perimetre/components/RuleModal.test.js
  ui/src/pages/perimetre/components/RuleUpdatesHistory.test.js
Labels: enhancement

#505 fix: find previous formation when key change
  server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
  server/src/jobs/formations/rcoConverter/tests/migrationFinder.test.js
Labels: bug

#506 feat: bump tco
  server/package.json
  server/yarn.lock
Labels: enhancement

#507 fix: no validate when creating sandbox formations
  server/src/common/utils/parcoursupUtils.js
  server/src/logic/updaters/mnaFormationUpdater.js
Labels: bug

#509 feat(affelnet): reorder match strength
  server/src/logic/controller/coverage.js
Labels: enhancement

#508 fix: no mongo id for mef sub schema
  server/src/common/model/schema/formation/formation.js
Labels: bug

#514 fix: update log schema for mongo logs
  server/src/common/model/schema/log.js
Labels: enhancement

#513 feat: clean status history PS
  server/migrations/20220210162942-clean-parcoursup-formation-statuts-history.js
  server/src/common/model/schema/parcoursupFormation.js
  server/src/http/routes/parcoursup.js
  server/src/jobs/parcoursup/reportRejected.js
  server/src/logic/common/utils/diffUtils.js
  server/src/logic/updaters/coverageUpdater.js
  ui/src/pages/admin/ReconciliationPs/ReconciliationPs.test.js
Labels: enhancement

#515 feature: Ajout d'indices relatifs à la consommation des différentes APIs
  server/src/common/model/index.js
  server/src/common/model/schema/consumption.js
  server/src/common/model/schema/index.js
  server/src/http/middlewares/consumptionMiddleware.js
  server/src/http/server.js
Labels: enhancement

#516 Fix/statistique counter
  server/migrations/20220215091117-clean-stats-counter.js
  server/src/common/model/schema/statistique.js
  server/src/http/routes/stats.js
  server/src/http/server.js
Labels: enhancement

#517 Feature/history status affelnet parcoursup
  server/migrations/20220215110549-limit-history-affelnet-parcoursup.js
  server/src/logic/updaters/tagsHistoryUpdater.js
Labels: enhancement

#520 Feature/remove archived rco training after 1 year
  server/migrations/20220215135326-limit-rcoformation-updates-history.js
  server/src/common/model/schema/rcoFormation.js
  server/src/jobs/formations/rcoImporter/importer/importer.js
Labels: enhancement

#521 chore: clean unused fields
  server/migrations/20220215165043-remove-unused-fields.js
  server/src/common/model/schema/formation/formation.js
  server/src/common/model/swaggerSchema/formation.js
  server/src/jobs/formations/rcoConverter/converter/converter.js
  server/src/logic/common/utils/diffUtils.js
  ui/src/common/components/formation/DescriptionBlock.test.js
  ui/src/common/components/formation/OrganismesBlock.test.js
  ui/src/pages/Formation/Formation.test.js
Labels: enhancement

#524 feat: published dates
  server/migrations/20220216111515-add-published-dates.js
  server/src/common/model/schema/formation/formation.js
  server/src/common/model/swaggerSchema/formation.js
  server/src/common/utils/historyUtils.js
  server/src/http/routes/parcoursup.js
  server/src/jobs/affelnet/perimetre/controller.js
  server/src/jobs/formations/rcoConverter/converter/migrationFinder.js
  server/src/jobs/parcoursup/export/index.js
  server/src/jobs/parcoursup/perimetre/controller.js
  server/src/logic/controller/reconciliation.js
  server/tests/unit/common/utils/historyUtils.test.js
  ui/src/common/components/Search/Search.js
  ui/src/common/components/Search/constantsFormations.js
  ui/src/common/components/formation/PublishModal.jsx
  ui/src/common/components/formation/PublishModal.test.js
  ui/src/locales/helpText.json
  ui/src/pages/Etablissement/Etablissement.js
  ui/src/pages/Formation/Formation.js
  ui/src/pages/admin/ReconciliationPs/components/ReconciliationModalHeader.jsx
  ui/src/pages/layout/components/AlertMessage.js
  ui/src/pages/layout/components/Header.js
  ui/src/pages/layout/components/NavigationMenu.js
Labels: enhancement

#525 tests: Add tests for UAIs validity in UI
  ui/src/common/utils/testUtils.js
  ui/src/pages/Etablissement/Etablissement.js
  ui/src/pages/Etablissement/Etablissement.test.js
  ui/src/pages/Formation/Formation.js
  ui/src/pages/Formation/Formation.test.js
Labels: tests

#526 feat: display parcoursup posting errors
  ui/src/pages/Formation/Formation.js
Labels: feature

#528 fix(ui): mobile display
  ui/src/common/components/CardListEtablissements/CardListEtablissements.js
  ui/src/common/components/Search/Search.js
  ui/src/common/components/Search/search.css
  ui/src/pages/ActionsExpertes/ActionsExpertes.jsx
  ui/src/pages/Etablissement/Etablissement.js
  ui/src/pages/Formation/Formation.js
Labels: enhancement

#530 test(ui): more tests on establishment page
  ui/src/common/api/organisme.js
  ui/src/common/utils/testUtils.js
  ui/src/pages/Etablissement/Etablissement.js
  ui/src/pages/Etablissement/Etablissement.test.js
  ui/src/pages/Formation/Formation.test.js
  ui/src/pages/perimetre/components/Diplome.test.js
Labels: tests

#531 fix: don't reset status badges for non-qualiopi
  server/src/jobs/affelnet/perimetre/controller.js
  server/src/jobs/parcoursup/perimetre/controller.js
Labels: bug

#532 refactor: pagination
  ui/src/common/components/Search/Search.js
Labels: enhancement

#533 Fix/improve paging
  server/src/common/esClient/mongoosastic/index.js
  ui/src/common/components/Search/Search.js
  ui/src/common/components/Search/components/Pagination.jsx
  ui/src/common/components/Search/search.css
Labels: enhancement

#534 fix: no more filter on rncp for parcoursup
  server/src/jobs/parcoursup/export/index.js
  server/src/jobs/parcoursup/tests/export.test.js
Labels: enhancement

#535 feat: affelnet import with key
  server/src/jobs/affelnet/coverage.js
  server/src/jobs/affelnet/tests/coverage.test.js
  server/src/logic/controller/coverage.js
Labels: enhancement

#537 Feature/test parcoursup coverage
  server/src/jobs/affelnet/tests/coverage.test.js
  server/src/jobs/parcoursup/tests/coverage.test.js
  server/src/logic/controller/coverage.js
Labels: tests

#538 feat: more digits on paging when close to start or close to end
  ui/src/common/components/Search/components/Pagination.jsx
Labels: enhancement

#541 fix: payload to update uai for etablissement
  ui/src/pages/Etablissement/Etablissement.js
Labels: bug
